name: Create pull

description: Creates a pull request

inputs:
  base:
    description: The base branch
    required: true
  head:
    description: The head branch
    required: true
  title:
    description: The title of the pull request
    required: true
  github_token:
    description: The GitHub token to use
    required: true
outputs:
  pull_number:
    description: The pull request number
    value: '${{ steps.create-pull.outputs.pull_number }}'

runs:
  using: composite
  steps:
    - name: Creating pull request
      id: create-pull
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const owner = 'JensDll'
          const repo = 'steganography'

          const { data: pullRequest } = await github.rest.pulls.create({
            owner,
            repo,
            base: '${{ inputs.base }}',
            head: '${{ inputs.head }}',
            title: '${{ inputs.title }}',
            body: '',
            commit_message: '${{ inputs.title }}',
          })

          core.setOutput('pull_number', pullRequest.number)
