apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web-cert
  namespace: services
spec:
  secretName: web-cert
  dnsNames:
    - steganography.app
    - www.steganography.app
  privateKey:
    algorithm: ECDSA
  issuerRef:
    kind: Issuer
    name: services-issuer
