apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
data:
  mime.types: |
    types {
      text/html html htm shtml;
      text/css css;

      image/svg+xml svg svgz;

      font/woff woff;
      font/woff2 woff2;

      application/javascript js;
    }

  nginx.conf: |
    load_module /usr/lib/nginx/modules/ngx_http_brotli_filter_module.so;
    load_module /usr/lib/nginx/modules/ngx_http_brotli_static_module.so;

    worker_processes auto;

    error_log /var/log/nginx/error.log notice;
    pid /tmp/nginx.pid;

    events {
      worker_connections 1024;
    }

    http {
      proxy_temp_path /tmp/proxy_temp;
      client_body_temp_path /tmp/client_temp;
      fastcgi_temp_path /tmp/fastcgi_temp;
      uwsgi_temp_path /tmp/uwsgi_temp;
      scgi_temp_path /tmp/scgi_temp;

      include /etc/nginx/mime.types;
      default_type application/octet-stream;
      charset_types text/css image/svg+xml application/javascript;

      log_format main
        '$remote_addr - [$time_local] '
        '[$request $status $body_bytes_sent] '
        '[$http_referer] [$http_user_agent]';

      access_log /var/log/nginx/access.log main;

      sendfile on;
      server_tokens off;

      keepalive_timeout 65;

      gzip on;
      gzip_static on;
      gzip_comp_level 6;
      gzip_types application/javascript;

      brotli on;
      brotli_static on;
      brotli_comp_level 4;
      brotli_types application/javascript;

      include /etc/nginx/conf.d/*.conf;
    }

  server.conf: |
    server {
      listen 8080 default_server;
      root /data/www;
      charset utf-8;
      if_modified_since off;
      etag off;

      location / {
        try_files $uri /index.html;
        add_header Cache-Control "no-cache";
        add_header Last-Modified "";
        add_header X-Content-Type-Options "nosniff";
      }

      location /etc {
        add_header Cache-Control "no-store";
        add_header Last-Modified "";
        add_header X-Content-Type-Options "nosniff";
      }

      location /assets {
        add_header Cache-Control "max-age=315360000, public, no-transform, immutable";
        add_header Last-Modified "";
        add_header X-Content-Type-Options "nosniff";
      }

      location /fonts {
        add_header Cache-Control "max-age=315360000, public, no-transform, immutable";
        add_header Last-Modified "";
        add_header X-Content-Type-Options "nosniff";
      }

      location = /health {
        access_log off;
        return 200;
      }
    }

  config.js: const $config={API:{URI:'https://api.doellamnn.xyz',RATE_LIMIT:120}}
