apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      service: web
  revisionHistoryLimit: 4
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: web
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: docker-pull
      containers:
        - name: web
          image: jensdll/image-data-hiding:web.new.2
          imagePullPolicy: Always
          securityContext:
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
            runAsNonRoot: true
            runAsUser: 101
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: nginx
              mountPath: /etc/nginx/
              readOnly: true
            - name: conf
              mountPath: /etc/nginx/conf.d/
              readOnly: true
            - name: etc
              mountPath: /data/www/etc/
              readOnly: true
          resources:
            requests:
              cpu: '100m'
              memory: '128Mi'
            limits:
              cpu: '200m'
              memory: '256Mi'
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
      volumes:
        - name: nginx
          configMap:
            name: web-config
            items:
              - key: nginx.conf
                path: nginx.conf
              - key: mime.types
                path: mime.types
        - name: conf
          configMap:
            name: web-config
            items:
              - key: server.conf
                path: server.conf
        - name: etc
          configMap:
            name: web-config
            items:
              - key: config.js
                path: config.js
