version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "staging"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/services/steganography.api"
    target-branch: "staging"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/services/steganography.api"
    target-branch: "staging"
    schedule:
      interval: "weekly"
