services:
  web:
    build: services/web
    volumes:
      - ./services/web/nginx/nginx/:/etc/nginx/
      - ./services/web/nginx/www/config.js:/data/www/config.js
    ports:
      - 4000:8080
    networks:
      - appnet
  api:
    build: services/api
    volumes:
      - ./services/api/src/WebApi/appsettings.json:/app/appsettings.json
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 4001:8080
    networks:
      - appnet
networks:
  appnet:
    driver: bridge
