version: "3.9"

services:
  proxy:
    image: traefik:v2.10.1
    ports:
      - 80:80
      - 443:443
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./services/steganography.traefik/traefik.yaml:/etc/traefik/traefik.yaml
    labels:
      - "traefik.http.routers.dashboard.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=traefik"
    networks:
      - appnet

  app:
    build:
      context: services/
      dockerfile: steganography.api/Dockerfile
    volumes:
      - ./services/steganography.api/deploy/kestrel/:/app/properties/
      - ./certs/steganography.api/:/usr/local/certs/
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.app.rule=HostSNI(`localhost`) || HostSNI(`www.localhost`)"
      - "traefik.tcp.routers.app.tls=true"
      - "traefik.tcp.routers.app.tls.passthrough=true"
      - "traefik.tcp.services.app.loadbalancer.server.port=8443"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
