ingressClass:
  enabled: true
ports:
  web:
    redirectTo: websecure
additionalArguments:
  - '--entrypoints.websecure.http.tls'
  - '--entrypoints.websecure.http.middlewares=traefik-buffering@kubernetescrd'
