apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: services-prod

resources:
  - namespace.yaml
  - issuer.yaml
  - ../../base

replacements:
  - source:
      kind: Issuer
      fieldPath: kind
    targets:
      - select:
          kind: Certificate
        fieldPaths:
          - spec.issuerRef.kind
  - source:
      kind: Issuer
      fieldPath: metadata.name
    targets:
      - select:
          kind: Certificate
        fieldPaths:
          - spec.issuerRef.name
