// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseButton: typeof import('./../src/components/base/BaseButton.vue')['default']
    BaseErrorList: typeof import('./../src/components/base/BaseErrorList.vue')['default']
    BaseFilePreview: typeof import('./../src/components/base/BaseFilePreview.vue')['default']
    BaseMarkdown: typeof import('./../src/components/base/BaseMarkdown.vue')['default']
    FormErrors: typeof import('./../src/components/form/FormErrors.vue')['default']
    FormFileInput: typeof import('./../src/components/form/FormFileInput.vue')['default']
    LoadingIndicator: typeof import('./../src/features/codec/components/LoadingIndicator.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./../src/components/layout/TheHeader.vue')['default']
    TheLogo: typeof import('./../src/components/layout/TheLogo.vue')['default']
    TheMain: typeof import('./../src/components/layout/TheMain.vue')['default']
    TheNav: typeof import('./../src/components/layout/TheNav.vue')['default']
    TheNavMobile: typeof import('./../src/components/layout/TheNavMobile.vue')['default']
  }
}
