// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppButton: typeof import('./../src/components/app/AppButton.vue')['default']
    AppFilePreview: typeof import('./../src/components/app/AppFilePreview.vue')['default']
    AppMarkdown: typeof import('./../src/components/app/AppMarkdown.vue')['default']
    AppProgressBar: typeof import('./../src/components/app/AppProgressBar.vue')['default']
    AppSection: typeof import('./../src/components/app/AppSection.vue')['default']
    FormErrors: typeof import('./../src/components/form/FormErrors.vue')['default']
    FormFileInput: typeof import('./../src/components/form/FormFileInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./../src/components/layout/TheHeader.vue')['default']
    TheMain: typeof import('./../src/components/layout/TheMain.vue')['default']
  }
}

export {}
