// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FormErrors: typeof import('./../src/components/form/FormErrors.vue')['default']
    FormFileInput: typeof import('./../src/components/form/FormFileInput.vue')['default']
    FormProvider: typeof import('./../src/components/form/FormProvider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./../src/components/layout/TheHeader.vue')['default']
    TheMain: typeof import('./../src/components/layout/TheMain.vue')['default']
    TheNav: typeof import('./../src/components/layout/TheNav.vue')['default']
    TheNavMobile: typeof import('./../src/components/layout/TheNavMobile.vue')['default']
    VButton: typeof import('./../src/components/app/VButton.vue')['default']
    VFilePreview: typeof import('./../src/components/app/VFilePreview.vue')['default']
    VMarkdown: typeof import('./../src/components/app/VMarkdown.vue')['default']
    VProgressBar: typeof import('./../src/components/app/VProgressBar.vue')['default']
  }
}
