apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-cert
  namespace: services
spec:
  secretName: api-cert
  dnsNames:
    - api.steganography.app
  privateKey:
    algorithm: ECDSA
  issuerRef:
    kind: Issuer
    name: services-issuer
