apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  appsettings.json: |
    {
      "Cors": {
        "AllowedOrigins": ["https://steganography.app"]
      },
      "Kestrel": {
        "Endpoints": {
          "Https": {
            "Url": "https://0.0.0.0:8443",
            "Path": "/usr/local/certs/tls.crt",
            "KeyPath": "/usr/local/certs/tls.key"
          }
        }
      }
    }
