apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web-cert
spec:
  commonName: imagedatahiding.com
  secretName: web-cert
  dnsNames:
    - imagedatahiding.com
    - www.imagedatahiding.com
  issuerRef:
    kind: _
    name: _
