global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: :443
  traefik:
    address: :9000

api:
  dashboard: true

providers:
  docker:
    exposedByDefault: false
