apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  appsettings.json: |
    {
      "Kestrel": {
        "Endpoints": {
          "Https": {
            "Url": "https://0.0.0.0:8443",
            "Path": "/usr/local/certs/tls.crt",
            "KeyPath": "/usr/local/certs/tls.key"
          }
        },
        "Limits": {
          "MaxRequestBodySize": 31457280
        }
      },
      "HttpHeaders": {
        "ContentSecurityPolicy": "default-src 'self';upgrade-insecure-requests;script-src 'self' 'sha256-8atrH6Pge+As3TgWrRwcD2pUDCYuTIBfIIqQGFDl3eA=';form-action 'none';img-src 'self' data: blob:; connect-src 'self' sentry.io;report-uri https://o4504621394165760.ingest.sentry.io/api/4504621566001152/security/?sentry_key=ab4ccfc57221482aafb411c6b9b4744a"
      }
    }
