apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web-cert
spec:
  commonName: dev.imagedatahiding.com
  dnsNames:
    - dev.imagedatahiding.com
    - www.dev.imagedatahiding.com
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-cert
spec:
  commonName: api.dev.imagedatahiding.com
  dnsNames:
    - api.dev.imagedatahiding.com
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: web-www-redirect
spec:
  redirectRegex:
    regex: ^https://www.dev.imagedatahiding.com(.*)
    replacement: https://dev.imagedatahiding.com${1}
