name: Format web

on:
  workflow_call:

jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: services/web
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v3

      - name: Using pnpm version 7.x.x
        uses: pnpm/action-setup@v2
        with:
          version: 7.x.x

      - name: Using node version 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
          cache-dependency-path: services/web/pnpm-lock.yaml

      - name: Installing dependencies
        run: pnpm install --frozen-lockfile

      - name: Formatting code
        run: pnpm run format

      - name: Preparing merge
        id: prepare
        run: |
          if ! git diff --quiet
          then
            TEMP_BRANCH=$(uuidgen)
            echo "::set-output name=TEMP_BRANCH::$TEMP_BRANCH"
            git config user.name github-actions
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            git checkout -b $TEMP_BRANCH
            git add --update
            git commit --message "github-actions: fix code style"
            git push origin $TEMP_BRANCH
          else
            echo "Nothing to commit!"
          fi

      - name: Creating pull request
        if: steps.prepare.outputs.TEMP_BRANCH != null
        id: create-pull
        uses: ./.github/actions/create-pull
        with:
          github_token: ${{ secrets.github_token }}
          base: staging
          head: ${{ steps.prepare.outputs.TEMP_BRANCH  }}
          title: 'github-actions: fix code style'

      - name: Merging pull request
        if: steps.create-pull.outputs.pull_number != null
        uses: ./.github/actions/merge-pull
        with:
          github_token: ${{ secrets.github_token }}
          pull_number: ${{ steps.create-pull.outputs.pull_number }}
          merge_method: 'github_squash'
          delete_head: true
