name: Main

on:
  pull_request:
    branches:
      - main
      - staging
  push:
    branches:
      - staging

jobs:
  should_run:
    uses: JensDll/should-run/.github/workflows/main.yaml@main
    with:
      projects: services/steganography.web services/steganography.api

  test_web:
    needs: should_run
    if:
      fromJSON(needs.should-run.outputs.result)['services/steganography.web'] == 'true' ||
      github.base_ref == 'main'
    uses: ./.github/workflows/test_steganography.web.yaml

  test_api:
    needs: should_run
    if:
      fromJSON(needs.should-run.outputs.result)['services/steganography.api'] == 'true' ||
      github.base_ref == 'main'
    uses: ./.github/workflows/test_steganography.api.yaml

  format_web:
    needs: should_run
    if: github.event_name == 'push' &&
      fromJSON(needs.should-run.outputs.result)['services/steganography.web'] == 'true'
    uses: ./.github/workflows/format_steganography.web.yaml

  format_api:
    needs: should_run
    if: github.event_name == 'push' &&
      fromJSON(needs.should-run.outputs.result)['services/steganography.api'] == 'true'
    uses: ./.github/workflows/format_steganography.api.yaml

  merge_main:
    needs:
      - test_web
      - test_api
    if: github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v3.5.2

      - name: Merging pull request
        uses: ./.github/actions/merge-pull
        with:
          # Make sure to trigger push workflows
          github_token: ${{ secrets.WORKFLOW_TOKEN }}
          pull_number: ${{ github.event.number }}
