name: Merge staging into main

on:
  workflow_dispatch:

jobs:
  create_pull:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v3.5.2

      - name: Creating pull request
        uses: ./.github/actions/create_pull
        with:
          # Make sure to trigger pull request workflows
          github_token: ${{ secrets.WORKFLOW_TOKEN }}
          base: main
          head: staging
          title: "github-actions: merge staging into main"
