name: Test web

on:
  workflow_call:

jobs:
  run:
    defaults:
      run:
        shell: bash
        working-directory: services/web
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v3

      - name: Using pnpm version 7.x.x
        uses: pnpm/action-setup@v2
        with:
          version: 7.x.x

      - name: Using node version 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
          cache-dependency-path: services/web/pnpm-lock.yaml

      - name: Installing dependencies
        run: pnpm install --frozen-lockfile

      - name: Running typecheck
        run: pnpm run typecheck

      - name: Checking for unfixable code style issues
        run: pnpm run lint --fix-dry-run

      - name: Building the project
        run: pnpm run build

      - name: Checking for no console statements
        run: pnpm run no-console
