name: Test steganography.web

on:
  pull_request:
    branches:
      - main
      - staging
  push:
    branches:
      - staging

jobs:
  should_run:
    uses: JensDll/should-run/.github/workflows/main.yaml@main
    with:
      projects: services/steganography.web

  test:
    needs: should_run
    if: fromJSON(needs.should_run.outputs.result)['services/steganography.web'] == 'true'
    defaults:
      run:
        shell: bash
        working-directory: services/steganography.web
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v4.1.1

      - name: Using pnpm version 8.x.x
        uses: pnpm/action-setup@v3.0.0
        with:
          version: 8.x.x

      - name: Using node version 20
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: services/steganography.web/pnpm-lock.yaml

      - name: Installing dependencies
        run: pnpm install --frozen-lockfile

      - name: Running typecheck
        run: pnpm run typecheck

      - name: Building the project
        run: pnpm run build

      - name: Checking for unfixable code style issues
        run: pnpm run lint --fix-dry-run

      - name: Checking for no console statements
        run: pnpm run lint:no-console
