name: Test web

on:
  workflow_call:

jobs:
  main:
    defaults:
      run:
        shell: bash
        working-directory: services/steganography.web
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v3.5.2

      - name: Using pnpm version 7.x.x
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.x.x

      - name: Using node version 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
          cache-dependency-path: services/web/pnpm-lock.yaml

      - name: Installing dependencies
        run: pnpm install --frozen-lockfile

      - name: Running typecheck
        run: pnpm run typecheck

      - name: Building the project
        run: pnpm run build

      - name: Checking for unfixable code style issues
        run: pnpm run lint --fix-dry-run

      - name: Checking for no console statements
        run: pnpm run lint:no-console
