name: Test api

on:
  workflow_call:

jobs:
  main:
    defaults:
      run:
        shell: bash
        working-directory: services/api
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v3

      - name: Setting up dotnet
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 7.0.x

      - name: Installing dependencies
        run: dotnet restore

      - name: Building the project
        run: dotnet build --configuration Release --no-restore

      - name: Running tests
        run: dotnet test --no-restore --verbosity normal
