apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: services-dev

secretGenerator:
  - name: dev-ca-cert
    files:
      - ca/tls.key
      - ca/tls.crt
    type: kubernetes.io/tls
generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yaml
  - issuer.yaml
  - ../../base

patchesJson6902:
  - target:
      version: v1alpha1
      kind: IngressRoute
      name: web-route
    patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: "Host(`dev.imagedatahiding.com`) || Host(`www.dev.imagedatahiding.com`)"
  - target:
      version: v1alpha1
      kind: IngressRoute
      name: api-route
    patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: "Host(`api.dev.imagedatahiding.com`)"

patchesStrategicMerge:
  - patches/domain.yaml
  - patches/config.yaml

replicas:
  - name: web-deploy
    count: 1
  - name: api-deploy
    count: 1

replacements:
  - source:
      kind: Issuer
      fieldPath: kind
    targets:
      - select:
          kind: Certificate
        fieldPaths:
          - spec.issuerRef.kind
  - source:
      kind: Issuer
      fieldPath: metadata.name
    targets:
      - select:
          kind: Certificate
        fieldPaths:
          - spec.issuerRef.name
