apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: test
spec:
  ipFamilyPolicy: PreferDualStack
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: my-app
