// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/app/AppButton.vue')['default']
    AppToggle: typeof import('./src/components/app/AppToggle.vue')['default']
    FormErrors: typeof import('./src/components/form/FormErrors.vue')['default']
    FormFileUpload: typeof import('./src/components/form/FormFileUpload.vue')['default']
    'Ic:twotoneRemoveCircle': typeof import('~icons/ic/twotone-remove-circle')['default']
    ImagePlusIcon: typeof import('./src/components/icon/ImagePlusIcon.vue')['default']
    LockClosedIcon: typeof import('./src/components/icon/LockClosedIcon.vue')['default']
    LockOpenIcon: typeof import('./src/components/icon/LockOpenIcon.vue')['default']
    'Mdi:github': typeof import('~icons/mdi/github')['default']
    TheHeader: typeof import('./src/components/layout/TheHeader.vue')['default']
    TheMain: typeof import('./src/components/layout/TheMain.vue')['default']
  }
}

export { }
